### ISSUE TITLE
arrow not working

### ISSUE THREAD

**Issue by vipul2012** [jamesinc/selectify#1]
hi,

this plugin is good but i think select box value should be change by arrow key.

Thanks!

**Comment by jamesinc** [comment]
Thanks for the feedback. I'll add keyboard support today.

**Comment by jamesinc** [comment]
Keyboard support has been added! Available in v1.0.5 in jQuery plugins repo.

Thanks @vipul2012 for bringing it to my attention.

**Comment by vipul2012** [comment]
Thanks for added Keyboard arrow supported.

other isse ::
1. i notice that change event fire on arrow press every time (i think change event not fire every time in native select)
2. i think you missing keyboard support (you can check native select)

you can check here :: http://jsfiddle.net/5bSYN/32/

Thanks!

**Comment by jamesinc** [comment]
That is how change events work normally. I have added an event handler to the other select element in the demo to demonstrate this.

http://jsfiddle.net/jamesinc/5bSYN/33/

If you focus the native select element (using TAB on the keyboard) and use the arrow keys, it will trigger change events every time.

The events are not quite the same when you have the drop down list open. I plan to address that in the next release, but seeing as I can't find reference to any browser that allows you to actually _expand_ a drop-down list using the keyboard, this scenario should be encountered by relatively few users.

It's also worth noting that different browsers may have different opinions on when to fire a change event. I haven't thoroughly checked this functionality yet. For now, it mirrors the default behaviour of Google Chrome.

As for pressing letters and numbers, that is a little more complicated. I'll have a go at implementing it, but I think the only way to do that would be to trigger the same keystroke events on the native select, then let its change event trigger an update to the overlay UI.

**Comment by jamesinc** [comment]
@vipul2012 the latest version implements matching keyboard-typing
