### ISSUE TITLE
revert selectify() method

### ISSUE THREAD

**Issue by shivabhusal** [jamesinc/selectify#4]
hi,
is there any way to revert the effect of the `selectify()` method?
when selectified.. it wraps the `<select>` elment with `<div>` s and all...
I need to revert this effect

**Comment by jamesinc** [comment]
Hi @shivabhusal, there is not revert functionality, but that's a good idea. I will write something now.

**Comment by jamesinc** [comment]
I've added this in version 1.1.8

You can un-selectify something by calling as follows:

``` js
$( element ).selectify( "remove" );
```

**Comment by shivabhusal** [comment]
great, thanks @jamesinc
